### ISSUE TITLE
Crash killing wither skells with the cleaver of beheading

### ISSUE THREAD

**Issue by LeoBeliik** [team-abnormals/savage-and-ravage#63] opened 2021-03-22 14:21 UTC
S&R v3.1.0
Crucial 2 modpack

I was killing wither skeletons with the cleaver of beheading, and the game crashed, it wasn't the first one I've killed tho.

https://gist.github.com/LeoBeliik/f3d3db48fb54d2aadf227fb5724596f2

**Comment by abigailfails** [comment] 2021-08-15 17:08
Hi, sorry for getting back on this so late but I'm pretty sure it isn't an issue with Savage & Ravage. I just checked the cleaver, and it doesn't have any special behaviour if it kills a mob that _isn't_ a player, so I don't see how it could cause this crash. Have you been able to reproduce it since then? Does it still happen when you hold other weapons?

**Comment by LeoBeliik** [comment] 2021-08-15 19:42
I haven't tested it after then, so I can't really confirm this was a problem with the cleaver or no, tho I'd assume it probably just was a coincidence and it's safe to close this.

**Comment by abigailfails** [comment] 2021-08-15 19:46
I'll close it, but feel free to reopen if you have the problem again.

**Closed by abigailfails** 2021-08-15 19:46 UTC
Labels: bug
